"""empty message

Revision ID: 4e7fc9feb8c1
Revises: 
Create Date: 2019-03-06 02:36:11.794371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e7fc9feb8c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doutor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('profissao', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('atendimento', 'alocacao', name='types'), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problema', sa.Text(), nullable=False),
    sa.Column('dh_agendamento_cliente', sa.Date(), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cidade', sa.String(length=80), nullable=True),
    sa.Column('bairro', sa.String(length=80), nullable=True),
    sa.Column('logradouro', sa.String(length=80), nullable=True),
    sa.Column('numero', sa.String(length=80), nullable=True),
    sa.Column('complemento', sa.String(length=80), nullable=True),
    sa.Column('longitude', sa.Float(precision=20, asdecimal=15), nullable=False),
    sa.Column('latitude', sa.Float(precision=20, asdecimal=15), nullable=False),
    sa.Column('tipo', sa.Enum('atendimento', 'alocacao', name='types'), nullable=False),
    sa.Column('id_tipo_servico', sa.Integer(), nullable=True),
    sa.Column('id_doutor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_doutor'], ['doutor.id'], ),
    sa.ForeignKeyConstraint(['id_tipo_servico'], ['tipo_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custo_atendimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_job', sa.Integer(), nullable=False),
    sa.Column('id_atendimento', sa.Integer(), nullable=False),
    sa.Column('id_doutor', sa.Integer(), nullable=False),
    sa.Column('dh_ult_encerramento', sa.Date(), nullable=False),
    sa.Column('dt_ciclo', sa.Date(), nullable=False),
    sa.Column('dt_previsao_pagamento', sa.Date(), nullable=False),
    sa.Column('dt_pagamento', sa.Date(), nullable=True),
    sa.Column('dt_ult_agendamento', sa.Date(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('trimestre', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('valor_atendimento', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.Column('valor_horas_extras', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.Column('valor_reembolso', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.Column('total_atendimento', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.ForeignKeyConstraint(['id_doutor'], ['doutor.id'], ),
    sa.ForeignKeyConstraint(['id_job'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custo_atendimento')
    op.drop_table('job')
    op.drop_table('tipo_servico')
    op.drop_table('pessoa')
    op.drop_table('doutor')
    # ### end Alembic commands ###
